const WILAYAT = [
  {
    code: 1,
    name: "Adrar",
    cities: [
      "Adrar",
      "Reggane",
      "Timimoun",
      "Aoulef",
      "Zaouiet Kounta",
      "Bouda",
      "Tsabit",
      "Fenoughil",
      "In Zghmir",
      "Tit",
      "Tamest",
      "Ouled Ahmed Timmi",
      "Sali",
      "Sebaa",
      "Tamekten",
      "Metarfa",
      "Ouled Aissa",
      "Tinerkouk",
      "Deldoul",
      "Talmine",
      "Ksar Kaddour",
      "Ouled Said",
      "Akabli",
    ],
  },
  {
    code: 2,
    name: "Chlef",
    cities: [
      "Chlef",
      "Ténès",
      "El Karimia",
      "Oued Fodda",
      "Ouled Fares",
      "Abou El Hassan",
      "Beni Haoua",
      "Bouzeghaia",
      "Dahra",
      "El Marsa",
      "Harchoun",
      "Herenfa",
      "Labiod Medjadja",
      "Moussadek",
      "Oued Goussine",
      "Oued Sly",
      "Sendjas",
      "Sidi Abderrahmane",
      "Sobha",
      "Tadjena",
      "Talassa",
      "Zeboudja",
      "Ain Merane",
      "Boukadir",
      "Breira",
      "Chettia",
      "El Hadjadj",
      "Ouled Ben Abdelkader",
      "Sidi Akkacha",
      "Taougrite",
      "Benairia",
      "Oum Drou",
      "Beni Rached",
      "El Karimia",
    ],
  },
  {
    code: 3,
    name: "Laghouat",
    cities: [
      "Laghouat",
      "Aflou",
      "Hassi R'Mel",
      "Brida",
      "Ksar El Hirane",
      "Aïn Madhi",
      "Bennacer Benchohra",
      "El Assafia",
      "El Ghicha",
      "Gueltat Sidi Saad",
      "Hadj Mechri",
      "Hassi Delaa",
      "Hassi R'Mel",
      "Oued Morra",
      "Sebgag",
      "Sidi Bouzid",
      "Tadjemout",
      "Tadjrouna",
      "Taouiala",
      "El Kheneg",
      "Sidi Makhlouf",
      "Beidha",
      "Oued M'zi",
    ],
  },
  {
    code: 4,
    name: "Oum El Bouaghi",
    cities: [
      "Oum El Bouaghi",
      "Aïn Beïda",
      "Aïn M'lila",
      "F'kirina",
      "Souk Naamane",
      "Aïn Babouche",
      "Aïn Diss",
      "Aïn Fakroun",
      "Aïn Kercha",
      "Aïn Zitoun",
      "Behir Chergui",
      "Berriche",
      "Bir Chouhada",
      "Dhalaa",
      "El Belala",
      "El Djazia",
      "El Fedjoudj Boughrara Sa",
      "El Harmilia",
      "Hanchir Toumghani",
      "Ksar Sbahi",
      "Meskiana",
      "Oued Nini",
      "Ouled Gacem",
      "Ouled Hamla",
      "Sigus",
      "Zorg",
      "Ouled Zouai",
      "El Amiria",
      "Boughrara Saoudi",
    ],
  },
  {
    code: 5,
    name: "Batna",
    cities: [
      "Batna",
      "Barika",
      "Timgad",
      "Merouana",
      "N'Gaous",
      "Aïn Djasser",
      "Aïn Touta",
      "Arris",
      "Amdoukal",
      "Boumia",
      "Bouzina",
      "Chemora",
      "Djerma",
      "El Madher",
      "Ghassira",
      "Ichmoul",
      "Kimmel",
      "Lazrou",
      "M'doukal",
      "Oued Chaaba",
      "Oued El Ma",
      "Rahbat",
      "Seggana",
      "Seriana",
      "Tazoult",
      "Teniet El Abed",
      "Tilatou",
      "Tkout",
      "Zanat El Beida",
      "Ouled Aouf",
      "Ouled Fadel",
      "Ouled Si Slimane",
      "Ras El Aioun",
      "T'Kout",
      "Talkhamt",
      "Theniet El Abed",
      "Taxlent",
      "Hidoussa",
      "Bitam",
      "Fesdis",
      "Foum Toub",
      "Gosbat",
      "Ouyoun El Assafir",
      "Tighanimine",
      "Lemsane",
      "Maafa",
      "Menaa",
      "Oued Taga",
      "Sefiane",
      "Tigharghar",
    ],
  },
  {
    code: 6,
    name: "Béjaïa",
    cities: [
      "Béjaïa",
      "Akbou",
      "Tichy",
      "Sidi Aïch",
      "Kherrata",
      "Adekar",
      "Aït R'zine",
      "Aït-Smail",
      "Akhfadou",
      "Amalou",
      "Amizour",
      "Aokas",
      "Barbacha",
      "Beni Djellil",
      "Beni Ksila",
      "Beni Maouche",
      "Boudjellil",
      "Bouhamza",
      "Chemini",
      "Darguina",
      "El Kseur",
      "Fenaia Il Maten",
      "Ighil Ali",
      "Kendira",
      "Leflaye",
      "Melbou",
      "Oued Ghir",
      "Semaoun",
      "Souk Oufella",
      "Tala Hamza",
      "Tamridjet",
      "Taskriout",
      "Tibane",
      "Tifra",
      "Tinebdar",
      "Timezrit",
      "Ait Jelil",
      "Ait Mouhli",
      "Akfadou",
      "Beni Mellikeche",
      "Beniksila",
      "Boukhelifa",
      "Colla",
      "Derguina",
      "Dra El Caid",
      "Feraoun",
      "Tamazirt",
      "Taourit Ighil",
      "Toudja",
    ],
  },
  {
    code: 7,
    name: "Biskra",
    cities: [
      "Biskra",
      "Tolga",
      "Ouled Djellal",
      "El Kantara",
      "Sidi Okba",
      "Ain Naga",
      "Ain Zaatout",
      "Bordj Ben Azzouz",
      "Bouchagroun",
      "Branis",
      "Chetma",
      "Djemorah",
      "El Feidh",
      "El Ghrous",
      "El Hadjeb",
      "El Haouch",
      "El Outaya",
      "Foughala",
      "Khenguet Sidi Nadji",
      "Lichana",
      "Lioua",
      "M'chouneche",
      "M'lili",
      "Meziraa",
      "Oumache",
      "Sidi Khaled",
      "Zeribet El Oued",
      "Ain Naga",
      "Bordj Chaiba",
      "Ouled Harkat",
      "Ouled Rahma",
      "Ouled Sassi",
    ],
  },
  {
    code: 8,
    name: "Béchar",
    cities: [
      "Béchar",
      "Kenadsa",
      "Béni Abbès",
      "Abadla",
      "Taghit",
      "Erg Ferradj",
      "Igli",
      "Lahmar",
      "Mogheul",
      "Ouled Khoudir",
      "Timoudi",
      "Ksabi",
      "Mechraa Houari Boumediene",
      "El Ouata",
      "Boukais",
      "Beni Ikhlef",
      "Tamtert",
      "Tabelbala",
      "Kerzaz",
      "Meridja",
      "Béni Ounif",
      "Beni Abbes",
      "Boudib",
      "Machraa Houari Boumediene",
    ],
  },
  {
    code: 9,
    name: "Blida",
    cities: [
      "Blida",
      "Boufarik",
      "Bougara",
      "Larbaa",
      "Mouzaia",
      "Aïn Romana",
      "Beni Mered",
      "Beni Tamou",
      "Ben Khelil",
      "Bouarfa",
      "Chiffa",
      "Djebabra",
      "El Affroun",
      "Guerrouaou",
      "Hammam Melouane",
      "Meftah",
      "Oued Djer",
      "Oued El Alleug",
      "Ouled Yaïch",
      "Soumaa",
      "Chebli",
      "Bouinan",
      "Chrea",
      "Chiffa",
      "Chraoua",
      "Sidi Moussa",
      "Bourkika",
      "Mouzaia",
    ],
  },
  {
    code: 10,
    name: "Bouira",
    cities: [
      "Bouira",
      "Lakhdaria",
      "Sour El Ghozlane",
      "Haizer",
      "Kadiria",
      "Aïn Bessem",
      "Aïn Laloui",
      "Aïn Turk",
      "Aomar",
      "Bechloul",
      "Bordj Okhriss",
      "Chorfa",
      "Dechmia",
      "Dirah",
      "El Adjiba",
      "El Asnam",
      "El Hachimia",
      "Guerrouma",
      "Hanif",
      "M'Chedallah",
      "Maala",
      "Oued El Berdi",
      "Raouraoua",
      "Ridane",
      "Saharidj",
      "Souk El Khemis",
      "Taghzout",
      "Z'barbar",
      "Ahl El Ksar",
      "Ait Laziz",
      "Aghbalou",
      "Ain El Hadjar",
      "Ath Mansour",
      "Bir Ghbalou",
      "Boukram",
      "Djebahia",
      "El Khabouzia",
      "El Mokrani",
      "Hadjera Zerga",
      "Taguedit",
      "Aomar",
    ],
  },
  {
    code: 11,
    name: "Tamanrasset",
    cities: [
      "Tamanrasset",
      "In Salah",
      "In Guezzam",
      "Abalessa",
      "Idles",
      "Tazrouk",
      "In Amguel",
      "In Ghar",
      "Tin Zaouatine",
      "Foggaret Ezzaouia",
      "In Amguel",
    ],
  },
  {
    code: 12,
    name: "Tébessa",
    cities: [
      "Tébessa",
      "Bir El Ater",
      "El Kouif",
      "Negrine",
      "Cheria",
      "Ouenza",
      "El Aouinet",
      "El Ma Labiodh",
      "Hammamet",
      "Bekkaria",
      "Bir Mokkadem",
      "Bir Dheheb",
      "Boukhadra",
      "El Meridj",
      "El Ogla",
      "El Ogla El Malha",
      "Ferkane",
      "Ain Zerga",
      "Gourigeur",
      "Morsott",
      "Oum Ali",
      "Safsaf El Ouesra",
      "Stah Guentis",
      "Tlidjene",
    ],
  },
  {
    code: 13,
    name: "Tlemcen",
    cities: [
      "Tlemcen",
      "Maghnia",
      "Remchi",
      "Ghazaouet",
      "Mansourah",
      "Nedroma",
      "Chetouane",
      "Sebdou",
      "Beni Snous",
      "Hennaya",
      "Bensekrane",
      "Ouled Mimoun",
      "Beni Bahdel",
      "Beni Boussaid",
      "Beni Mester",
      "Beni Ouarsous",
      "Dar Yaghmouracene",
      "El Aricha",
      "El Bouihi",
      "El Gor",
      "Fellaoucene",
      "Honaine",
      "Marsa Ben M'Hidi",
      "M'Sirda Fouaga",
      "Oued Lakhdar",
      "Sabra",
      "Sidi Abdelli",
      "Souk Tlata",
      "Souahlia",
      "Ain Fezza",
      "Ain Ghoraba",
      "Ain Kebira",
      "Ain Nehala",
      "Ain Youcef",
      "Amieur",
      "Azails",
      "Bouhlou",
      "Djebala",
      "Hamma Bouziane",
      "Sidi Djillali",
      "Sidi Medjahed",
      "Souk Tlata",
      "Tient",
      "Tlemcen Ouled Riyah",
      "Zenata",
    ],
  },
  {
    code: 14,
    name: "Tiaret",
    cities: [
      "Tiaret",
      "Frenda",
      "Sougueur",
      "Mahdia",
      "Dahmouni",
      "Ksar Chellala",
      "Rahouia",
      "Hamadia",
      "Medroussa",
      "Ain Deheb",
      "Medrissa",
      "Ain Kermes",
      "Ain Bouchekif",
      "Takhemaret",
      "Mechraa Safa",
      "Mellakou",
      "Sidi Ali Mellal",
      "Serghine",
      "Bougara",
      "Rechaiga",
      "Guertoufa",
      "Sidi Hosni",
      "Tagdemt",
      "Sebaine",
      "Tidda",
      "Nadorah",
      "Oued Lilli",
      "Sidi Abderrahmane",
      "Tousnina",
      "Zmalet El Emir Abdelkader",
      "Chehaima",
      "Djillali Ben Amar",
      "Madna",
      "Meghila",
      "Naima",
      "Sebaine",
      "Sebt",
      "Si Abdelghani",
      "Tagdempt",
      "Tircine",
    ],
  },
  {
    code: 15,
    name: "Tizi Ouzou",
    cities: [
      "Tizi Ouzou",
      "Azazga",
      "Draa Ben Khedda",
      "Boghni",
      "Ouadhia",
      "Draa El Mizan",
      "Ain El Hammam",
      "Beni Douala",
      "Larbaa Nath Irathen",
      "Makouda",
      "Tizi Rached",
      "Tizi Gheniff",
      "Bouzeguene",
      "Tigzirt",
      "Ouacif",
      "Mekla",
      "Iferhounene",
      "Assi Youcef",
      "Tadmait",
      "Freha",
      "Ait Yahia",
      "Ait Mahmoud",
      "Akbil",
      "Agouni Gueghrane",
      "Ain Zaouia",
      "Ait Aggouacha",
      "Ait Bouaddou",
      "Ait Boumahdi",
      "Ait Chafaa",
      "Ait Khellili",
      "Ait Oumalou",
      "Ait Toudert",
      "Ait Yahia Moussa",
      "Akerrou",
      "Assi Youcef",
      "Azeffoun",
      "Beni Aissi",
      "Beni Ziki",
      "Beni Zmenzer",
      "Boudjima",
      "Bounouh",
      "Iboudrarene",
      "Frikat",
      "Ifigha",
      "Iflissen",
      "Illilten",
      "Illoula Oumalou",
      "Imkiren",
      "Imsouhel",
      "Irdjen",
      "Maatkas",
      "Mechetraia",
      "Mizrana",
      "Ouaguenoun",
      "Souama",
      "Souk El Tenine",
      "Tirmitine",
      "Timizart",
      "Yakourene",
      "Yatafen",
      "Zekri",
    ],
  },
  {
    code: 16,
    name: "Alger",
    cities: [
      "Alger Centre",
      "Bab El Oued",
      "El Harrach",
      "Kouba",
      "Hussein Dey",
      "Sidi M'Hamed",
      "Dar El Beida",
      "Bab Ezzouar",
      "Bir Mourad Raïs",
      "Bordj El Kiffan",
      "Birtouta",
      "Bologhine",
      "Oued Smar",
      "El Magharia",
      "Bachdjerrah",
      "Baraki",
      "Bourouba",
      "Casbah",
      "Chéraga",
      "Dely Ibrahim",
      "Douera",
      "Draria",
      "El Achour",
      "El Biar",
      "Gué de Constantine",
      "Hammamet",
      "Hydra",
      "Les Eucalyptus",
      "Mohammadia",
      "Ouled Fayet",
      "Rahmania",
      "Reghaia",
      "Rouiba",
      "Souidania",
      "Staoueli",
      "Tessala El Merdja",
      "Zeralda",
      "Ain Benian",
      "Ain Taya",
      "Baba Hassen",
      "Belouizdad",
      "Ben Aknoun",
      "Birkhadem",
      "Bordj El Bahri",
      "Bouzareah",
      "Djasr Kasentina",
      "El Marsa",
      "H'Raoua",
      "Mahelma",
      "Rais Hamidou",
      "Rovigo",
      "Saoula",
      "Sidi Moussa",
    ],
  },
  {
    code: 17,
    name: "Djelfa",
    cities: [
      "Djelfa",
      "Aïn Oussera",
      "Messaad",
      "Hassi Bahbah",
      "Charef",
      "Birine",
      "El Idrissia",
      "Dar Chioukh",
      "Had Sahary",
      "Guernini",
      "Ain El Ibel",
      "Faidh El Botma",
      "Zaafrane",
      "Bouira Lahdab",
      "Ain Chouhada",
      "Ain Fekka",
      "Ain Maabed",
      "Amourah",
      "Benhar",
      "Beni Yacoub",
      "Deldoul",
      "Douis",
      "El Guedid",
      "Guettara",
      "Hassi Fedoul",
      "Hassi El Euch",
      "Mliliha",
      "Moudjebara",
      "M'Liliha",
      "Oum Laadham",
      "Sed Rahal",
      "Selmana",
      "Sidi Baizid",
      "Sidi Ladjel",
      "Tadmit",
      "Zaccar",
    ],
  },
  {
    code: 18,
    name: "Jijel",
    cities: [
      "Jijel",
      "El Milia",
      "Taher",
      "Chekfa",
      "Settara",
      "Kaous",
      "Texenna",
      "Sidi Abdelaziz",
      "Ziama Mansouriah",
      "El Ancer",
      "Djimla",
      "Emir Abdelkader",
      "Ouled Yahia Khadrouche",
      "Selma Benziada",
      "Ouled Rabah",
      "El Aouana",
      "Boussif Ouled Askeur",
      "Bordj Tahar",
      "Bouraoui Belhadef",
      "Chahna",
      "Djemaa Beni Habibi",
      "El Kennar Nouchfi",
      "Eraguene",
      "Ghebala",
      "Oudjana",
      "Sidi Maarouf",
      "Boudria Beni Yadjis",
      "Kheiri Oued Adjoul",
    ],
  },
  {
    code: 19,
    name: "Sétif",
    cities: [
      "Sétif",
      "El Eulma",
      "Aïn Oulmene",
      "Bougaa",
      "Beni Ourtilane",
      "Ain Arnat",
      "Ain El Kebira",
      "Ain Azel",
      "Ain Abessa",
      "Babor",
      "Bazer Sakhra",
      "Beni Aziz",
      "Beni Chebana",
      "Beni Fouda",
      "Beni Hocine",
      "Beida Bordj",
      "Bellaa",
      "Bir El Arch",
      "Bir Haddada",
      "Bouandas",
      "Bousselam",
      "Dehamcha",
      "Djemila",
      "Draa Kebila",
      "El Ouldja",
      "El Ouricia",
      "Guidjel",
      "Guellal",
      "Guenzet",
      "Guelta Zerka",
      "Hammam Guergour",
      "Hammam Sokhna",
      "Harbil",
      "Ksar El Abtal",
      "Maaouia",
      "Maouklane",
      "Mezloug",
      "Oued El Bared",
      "Ouled Addouane",
      "Ouled Sabor",
      "Ouled Si Ahmed",
      "Ouled Tebben",
      "Rasfa",
      "Salah Bey",
      "Serdj El Ghoul",
      "Talaifacene",
      "Taya",
      "Tella",
      "Tizi N'Bechar",
    ],
  },
  {
    code: 20,
    name: "Saïda",
    cities: [
      "Saïda",
      "Aïn El Hadjar",
      "Youb",
      "El Hassasna",
      "Doui Thabet",
      "Ouled Brahim",
      "Sidi Boubekeur",
      "Moulay Larbi",
      "Sidi Amar",
      "Maamora",
      "Ain Sekhouna",
      "Ain Soltane",
      "Ouled Khaled",
      "Sidi Ahmed",
      "Tircine",
      "Hounet",
    ],
  },
  {
    code: 21,
    name: "Skikda",
    cities: [
      "Skikda",
      "Collo",
      "El Harrouch",
      "Azzaba",
      "Tamalous",
      "Ain Zouit",
      "Zitouna",
      "Oum Toub",
      "Ramdan Djamel",
      "Benazouz",
      "Ain Cherchar",
      "Ain Kechra",
      "Ain Bouziane",
      "Bekkouche Lakhdar",
      "Ben Azzouz",
      "Bin El Ouiden",
      "Beni Bechir",
      "Beni Oulbane",
      "Beni Zid",
      "Bouchtata",
      "Cheraia",
      "Djendel Saadi Mohamed",
      "El Ghedir",
      "El Hadaiek",
      "Emjez Edchich",
      "Es Sebt",
      "Filfila",
      "Hamadi Krouma",
      "Kanoua",
      "Kerkera",
      "Kheneg Mayoum",
      "Oued Zehour",
      "Ouled Attia",
      "Ouled Hbaba",
      "Ramdane Djamel",
      "Salah Bouchaour",
      "Sidi Mezghiche",
      "Zerdaza",
    ],
  },
  {
    code: 22,
    name: "Sidi Bel Abbès",
    cities: [
      "Sidi Bel Abbès",
      "Télagh",
      "Sfisef",
      "Aïn El Berd",
      "Ben Badis",
      "Mostefa Ben Brahim",
      "Marhoum",
      "Merine",
      "Tenira",
      "Moulay Slissen",
      "Ain Adden",
      "Ain El Berd",
      "Ain Kada",
      "Ain Thrid",
      "Ain Tindamine",
      "Amarnas",
      "Badredine El Mokrani",
      "Belarbi",
      "Beni Chaib",
      "Benachiba Chelia",
      "Bir El Hammam",
      "Boudjebaa El Bordj",
      "Boukhanafis",
      "Chettouane Belaila",
      "Dhaya",
      "El Hacaiba",
      "Hassi Dahou",
      "Hassi Zehana",
      "Lamtar",
      "M'Cid",
      "Makedra",
      "Mezaourou",
      "Mostefa Ben Brahim",
      "Moulay Slissen",
      "Oued Sefioun",
      "Oued Taourira",
      "Redjem Demouche",
      "Ras El Ma",
      "Sehala Thaoura",
      "Sidi Ali Benyoub",
      "Sidi Brahim",
      "Sidi Chaib",
      "Sidi Dahou Zairs",
      "Sidi Hamadouche",
      "Sidi Khaled",
      "Sidi Lahcene",
      "Sidi Yacoub",
      "Tabia",
      "Tafissour",
      "Taoudmout",
      "Teghalimet",
      "Telagh",
      "Tenira",
      "Tilmouni",
      "Zerouala",
    ],
  },
  {
    code: 23,
    name: "Annaba",
    cities: ["Annaba", "El Bouni", "Berrahal", "Seraïdi", "Chorfa"],
  },
  {
    code: 24,
    name: "Guelma",
    cities: [
      "Guelma",
      "Boumahra Ahmed",
      "Oued Zenati",
      "Hammam Debagh",
      "Héliopolis",
    ],
  },
  {
    code: 25,
    name: "Constantine",
    cities: [
      "Constantine",
      "El Khroub",
      "Hamma Bouziane",
      "Aïn Smara",
      "Didouche Mourad",
    ],
  },
  {
    code: 26,
    name: "Médéa",
    cities: ["Médéa", "Berrouaghia", "Aïn Boucif", "Ouzera", "Tablat"],
  },
  {
    code: 27,
    name: "Mostaganem",
    cities: [
      "Mostaganem",
      "Aïn Tedeles",
      "Hassi Mameche",
      "Mazagran",
      "Bouguirat",
    ],
  },
  {
    code: 28,
    name: "Msila",
    cities: ["Msila", "Bousaada", "Aïn El Hadjel", "Sidi Aïssa", "Magra"],
  },
  {
    code: 29,
    name: "Mascara",
    cities: ["Mascara", "Tighennif", "Sig", "Bouhanifia", "Oued Taria"],
  },
  {
    code: 30,
    name: "Ouargla",
    cities: [
      "Ouargla",
      "Touggourt",
      "Hassi Messaoud",
      "El Hadjira",
      "Temacine",
    ],
  },
  {
    code: 31,
    name: "Oran",
    cities: ["Oran", "Es Senia", "Bir El Djir", "Arzew", "Gdyel"],
  },
  {
    code: 32,
    name: "El Bayadh",
    cities: ["El Bayadh", "Rogassa", "Bougtob", "Chellala", "Brezina"],
  },
  {
    code: 33,
    name: "Illizi",
    cities: ["Illizi", "Djanet", "Bordj Omar Driss"],
  },
  {
    code: 34,
    name: "Bordj Bou Arréridj",
    cities: [
      "Bordj Bou Arréridj",
      "El Achir",
      "Ras El Oued",
      "Bir Kasdali",
      "Djaafra",
    ],
  },
  {
    code: 35,
    name: "Boumerdès",
    cities: [
      "Boumerdès",
      "Thenia",
      "Boudouaou",
      "Dellys",
      "Baghlia",
      "Afir",
      "Ben Choud",
      "Bordj Menaïel",
      "Cap Djinet",
      "Corso",
      "Djinet",
      "El Kharrouba",
      "Hammedi",
      "Isser",
      "Khemis El Khechna",
      "Larbatache",
      "Leghata",
      "Naciria",
      "Ouled Aissa",
      "Ouled Hedadj",
      "Si Mustapha",
      "Souk El Had",
      "Taourga",
      "Tidjelabine",
      "Timezrit",
      "Zemmouri",
    ],
  },
  {
    code: 36,
    name: "El Tarf",
    cities: ["El Tarf", "Ben M'hidi", "Bouhadjar", "Dréan", "El Kala"],
  },
  {
    code: 37,
    name: "Tindouf",
    cities: ["Tindouf"],
  },
  {
    code: 38,
    name: "Tissemsilt",
    cities: [
      "Tissemsilt",
      "Bordj Emir Khaled",
      "Theniet El Had",
      "Lazharia",
      "Khemisti",
    ],
  },
  {
    code: 39,
    name: "El Oued",
    cities: ["El Oued", "Robbah", "Bayadha", "Guemar", "Magrane"],
  },
  {
    code: 40,
    name: "Khenchela",
    cities: ["Khenchela", "Aïn Touila", "El Hamma", "Babar", "Kais"],
  },
  {
    code: 41,
    name: "Souk Ahras",
    cities: ["Souk Ahras", "Sedrata", "Mechroha", "Taoura", "Hanancha"],
  },
  {
    code: 42,
    name: "Tipaza",
    cities: ["Tipaza", "Cherchell", "Bou Ismail", "Gouraya", "Hadjeret Ennous"],
  },
  {
    code: 43,
    name: "Mila",
    cities: [
      "Mila",
      "Chelghoum Laid",
      "Ferdjioua",
      "Tassadane Haddada",
      "Grarem Gouga",
    ],
  },
  {
    code: 44,
    name: "Aïn Defla",
    cities: ["Aïn Defla", "Khemis Miliana", "Miliana", "El Attaf", "Rouina"],
  },
  {
    code: 45,
    name: "Naâma",
    cities: ["Naâma", "Mecheria", "Aïn Sefra", "Tiout", "Sfissifa"],
  },
  {
    code: 46,
    name: "Aïn Témouchent",
    cities: [
      "Aïn Témouchent",
      "El Amria",
      "Hammam Bouhadjar",
      "Beni Saf",
      "Oulhaça El Gheraba",
    ],
  },
  {
    code: 47,
    name: "Ghardaïa",
    cities: ["Ghardaïa", "Berriane", "Metlili", "El Atteuf", "Bounoura"],
  },
  {
    code: 48,
    name: "Relizane",
    cities: [
      "Relizane",
      "Oued Rhiou",
      "Mazouna",
      "Zemmoura",
      "Sidi M'Hamed Ben Ali",
    ],
  },
  {
    code: 49,
    name: "Timimoun",
    cities: ["Timimoun", "Ouled Said", "Tinerkouk", "Aougrout", "Deldoul"],
  },
  {
    code: 50,
    name: "Bordj Badji Mokhtar",
    cities: ["Bordj Badji Mokhtar", "Timiaouine"],
  },
  {
    code: 51,
    name: "Ouled Djellal",
    cities: ["Ouled Djellal", "Doucen", "Sidi Khaled", "Ras El Miad"],
  },
  {
    code: 52,
    name: "Béni Abbès",
    cities: ["Béni Abbès", "Kerzaz", "Beni Ikhlef", "Tamtert", "Timoudi"],
  },
  { code: 53, name: "In Salah", cities: ["In Salah", "Foggaret Ezzaouia"] },
  { code: 54, name: "In Guezzam", cities: ["In Guezzam", "Tin Zaouatine"] },
  {
    code: 55,
    name: "Touggourt",
    cities: ["Touggourt", "Nezla", "El Hadjira", "Temacine", "Megarine"],
  },
  { code: 56, name: "Djanet", cities: ["Djanet", "Bordj El Haouas"] },
  {
    code: 57,
    name: "El M'Ghair",
    cities: ["El M'Ghair", "Djamaa", "Sidi Khelil", "Oum Touyour", "M'Rara"],
  },
  {
    code: 58,
    name: "El Menia",
    cities: ["El Menia", "Hassi Gara", "Mansoura"],
  },
];

export default WILAYAT;
